---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: "sc-cdro" 
provisioner: efs.csi.aws.com
reclaimPolicy: Delete
volumeBindingMode: Immediate
parameters:
  provisioningMode: efs-ap
  fileSystemId: "fs-094e786238df295bb" # EKS 새로 배포시 바뀜 
  directoryPerms: "777"
  gid: "0"
  uid: "0"